apiVersion: v1
kind: Secret
metadata:
  name: token-private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/ITBeyder/argocd-course.git
  username: ITBeyder
  password: <TOKEN>